// This file was auto-generated by ML.NET Model Builder.
using Microsoft.AspNetCore.Mvc;
//using System.Web.Http;
using ObSecureApp.Models;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ObSecureApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SentimentEngineController : ControllerBase
    {
       
        [HttpGet("{text}")]
        public string Get(string text)
        {
            SentimentML sentimentML = new SentimentML();

            SentimentPrediction sentimentPrediction = sentimentML.Predict(text);

            string result = string.Format("{}-{}", sentimentPrediction.Prediction, sentimentPrediction.Probability);

            return result;
        }
        // POST api/<SentimentEngineController>
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT api/<SentimentEngineController>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/<SentimentEngineController>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}
